### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by probonopd** [azubieta/appimage-appsdir#2]
Some users might confuse "appsdir" with "AppDir". At least that's what my first impression was. Maybe "apps folder" would be a name with less potential for confusion?

(Also, directories are what the computer sees. Folders are what the user sees in the GUI. Normally, Unix directories are "backing" what is presented to the user as folders, but that does not always have to be the case.)

**Comment by azubieta** [comment]
Seems fair, project renamed.
